class not_found_exception(Exception):
    pass